### ISSUE TITLE
components skeleton file or sample in views folder

### ISSUE THREAD

**Issue by powerplayguy** [dhinesh03/mithril-starter-kit#1]
hi. i am at loss.
i need to write a component and load it in a view. i haven't have any successes so far. i am at loss. can you guide me on how to write a component in component folder? thanks

**Comment by dhinesh03** [comment]
Hi @powerplayguy  ,

Hope you can see the following message on the browser while you run the "npm start" command.
![screenshot 2018-01-16 15 10 53](https://user-images.githubusercontent.com/750200/34982276-fecff0aa-facf-11e7-8ce9-8f9dfa2c50dd.png)

Then try the following

- Create a sample-component.js file under views/components folder
- Add the following code

```
var count = 0; // added a variable
module.exports = {
    view: function() {
        return m('main', [
            m('h1', {
                class: 'title'
            }, 'My first component'),
            // changed the next line
            m('button', {
                onclick: function() {
                    count++;
                }
            }, count + ' clicks'),
        ]);
    },
};
```

- Add the following line on top of views/landing-page.js
`import SampleComponent from '../views/components/sample-component';`

- And invoke the component from landing-page.js -> view function
```
view: function(/*vnode*/) {
            return m('div', [
                m('h2', 'Congratulations, you made it!'),
                m('p', 'You\'ve spun up your very first Mithril app :-)'),
                m(SampleComponent),
            ]);
        },
```

**Comment by powerplayguy** [comment]
yeah it works. thanks ! i have one more issue. how do i call a parent function from inside a component?

**Comment by dhinesh03** [comment]
You can pass the function reference as args and can access via vnode.attrs. Refer the [document](https://mithril.js.org/vnodes.html)
